# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('event_type', models.IntegerField(choices=[(1, 'Добавление нового расходника'), (2, 'Передача расходника в пользование'), (3, 'Передача расходники на заправку'), (4, 'Утилизация'), (5, 'Передача пустого расходника на склад'), (6, 'Создание нового пользователя'), (7, 'Удаление пользователя')], null=True)),
                ('text', models.CharField(max_length=256)),
            ],
        ),
    ]
