# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 15:26
from __future__ import unicode_literals

from django.db import migrations, models


def convert_numbers(apps, schema_editor):
    Events = apps.get_model("events", "Events")
    for item in Events.objects.all():
        item.cart_number = str(item.cart_number)
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='cart_number',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
    migrations.RunPython(convert_numbers),
    ]
