# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160829_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cart_old_number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('AD', 'Adding a new consumables'), ('ADE', 'Adding a new empty cartriges'), ('TR', 'Transfer consumables for use'), ('TF', 'Transfer Consumables for refueling'), ('RS', 'Return to the remanufactured cartridge on storage'), ('TB', 'Move to basket'), ('DC', 'Delete cartridge'), ('TS', 'Passing an empty consumables stock'), ('CU', 'Creating a new user'), ('DU', 'Removing a user'), ('CN', 'Change number')], max_length=32),
        ),
    ]
