# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('address', models.CharField(max_length=512)),
                ('default', models.BooleanField(default=False)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.OrganizationUnits')),
            ],
        ),
    ]
