# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-18 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storages',
            name='departament',
        ),
        migrations.DeleteModel(
            name='Storages',
        ),
    ]
