# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storages',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storages',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
