# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnconUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Login')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('fio', models.CharField(blank=True, max_length=256, null=True, verbose_name='Full name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('departament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.OrganizationUnits', verbose_name='Organization unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
