# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20151219_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='anconuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
