# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=256)),
                ('date_created', models.DateField(db_index=True, null=True)),
                ('firm', models.CharField(max_length=256)),
                ('user', models.CharField(max_length=256, null=True)),
                ('json_content', models.TextField()),
                ('money', models.IntegerField(db_index=True, null=True)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.OrganizationUnits')),
            ],
        ),
        migrations.CreateModel(
            name='SCDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=256)),
                ('date_of_signing', models.DateField(blank=True, db_index=True, null=True)),
                ('date_created', models.DateField(db_index=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('short_cont', models.TextField(null=True)),
                ('money', models.IntegerField(db_index=True, null=True)),
                ('spent', models.IntegerField(db_index=True, null=True)),
                ('doc_type', models.IntegerField(choices=[(1, 'Delivery agreement'), (2, 'Service agreement'), (3, 'Deed of conveyance'), (4, 'Act of write-off')])),
                ('user', models.CharField(max_length=256, null=True)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.OrganizationUnits')),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.FirmTonerRefill')),
            ],
        ),
        migrations.AddField(
            model_name='refillingcart',
            name='parent_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.SCDoc'),
        ),
    ]
