# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refillingcart',
            name='doc_type',
            field=models.IntegerField(choices=[(1, 'To firm'), (2, 'From firm')], default=1),
        ),
    ]
