# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scdoc',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
