# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20160428_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scdoc',
            name='doc_type',
            field=models.IntegerField(choices=[(1, 'Delivery agreement'), (2, 'Service agreement'), (3, 'Deed of conveyance'), (4, 'Act of write-off')]),
        ),
    ]
