# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20160428_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scdoc',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
