# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20160430_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scdoc',
            name='date',
        ),
        migrations.AddField(
            model_name='scdoc',
            name='date_of_signing',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
