# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20160430_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='scdoc',
            name='parent_doc',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
