# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_scdoc_parent_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=256)),
                ('date_created', models.DateField(db_index=True, null=True)),
                ('firm', models.CharField(max_length=256)),
                ('user', models.CharField(max_length=256, null=True)),
                ('json_content', models.TextField()),
                ('money', models.IntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scdoc',
            name='parent_doc',
        ),
        migrations.AddField(
            model_name='refillingcart',
            name='parent_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.SCDoc'),
        ),
    ]
