# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20160416_1744'),
        ('docs', '0006_auto_20160505_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='refillingcart',
            name='departament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.OrganizationUnits'),
            preserve_default=False,
        ),
    ]
