# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='use_ssl',
            field=models.NullBooleanField(),
        ),
    ]
