# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20160830_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='print_name_obj',
            field=models.BooleanField(default=True),
        ),
    ]
