# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20160406_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='use_tls',
            field=models.NullBooleanField(),
        ),
    ]
