# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_settings_use_tls'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='page_format',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
