# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20160830_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='print_name_ou',
            field=models.BooleanField(default=True),
        ),
    ]
