# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_settings_print_name_ou'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='show_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='time_zone',
            field=models.CharField(default='Asia/Yekaterinburg', max_length=64, null=True),
        ),
    ]
