# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_settings_page_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='page_format',
            field=models.CharField(default='A4', max_length=2, null=True),
        ),
    ]
