# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20160415_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='use_ssl',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='use_tls',
            field=models.NullBooleanField(default=False),
        ),
    ]
