# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20160611_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='use_tls',
            field=models.BooleanField(default=False),
        ),
    ]
