# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridgeitemname',
            name='cart_itm_name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
