# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager

def convert_numbers(apps, schema_editor):
    CartridgeItem = apps.get_model("index", "CartridgeItem")
    for item in CartridgeItem.objects.all():
        item.cart_number = str(item.cart_number)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20160717_0859'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizationunits',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='cartridgeitem',
            name='cart_number',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.RunPython(convert_numbers),
    ]
