# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20160829_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridgeitem',
            name='cart_number_postfix',
        ),
    ]
