# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_numerator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerator',
            name='departament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.OrganizationUnits'),
        ),
    ]
