# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_cartridgeitem_cart_number_postfix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridgeitem',
            name='cart_date_added',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cartridgeitem',
            name='cart_date_change',
            field=models.DateTimeField(db_index=True),
        ),
    ]
