# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20160416_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridgeitem',
            name='stor',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
