# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20151219_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='departament',
        ),
        migrations.AlterModelManagers(
            name='organizationunits',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='cartridgeitem',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cartridgeitem',
            name='cart_status',
            field=models.IntegerField(choices=[(1, 'Full in stock'), (2, 'In use'), (3, 'Empty in stock'), (4, 'Filled in firm'), (5, 'Full in basket'), (6, 'Empty in basket')], default=1),
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
