# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20160104_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='cart_itm',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
