# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_cartridgeitem_stor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartridgeitem',
            old_name='stor',
            new_name='sklad',
        ),
    ]
