# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20161008_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridgeitem',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
