# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20160517_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmtonerrefill',
            name='firm_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.City', verbose_name='Select city'),
        ),
    ]
