# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_cartridgeitem_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmtonerrefill',
            name='vote_minus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='firmtonerrefill',
            name='vote_plus',
            field=models.IntegerField(default=0),
        ),
    ]
