# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_cartridgeitem_bufer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridgeitem',
            name='sklad',
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('address', models.CharField(max_length=512)),
                ('default', models.BooleanField(default=False)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.OrganizationUnits')),
            ],
        ),
        migrations.AddField(
            model_name='cartridgeitem',
            name='stor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Storages'),
        ),
    ]
