# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 18:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20160212_1452'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizationunits',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
