
from django.conf.urls import url
from index.api.views import (   ajax_add_session_items, 
                                ajax_add_session_items_from_barcode,
                                city_list,
                                del_node,
                                names_suggests, 
                                turf_cartridge,
                                clear_session,
                                transfer_to_stock,
                                del_firm,
                                transfer_to_basket,
                                get_cart_ou,
                                move_to_use,
                                view_events,
                                transfer_to_firm,
                                from_basket_to_stock,
                                change_ou_name,
                                add_object_to_basket_for_firm,
                                force_move_to_transfer,
                                remove_session_item,
                                move_objects_to_firm_with_barcode,
                                add_object_to_basket_from_firm_to_stock,
                                rate,
                                change_cart_number,
                                clear_basket_session,
                            )
from accounts.api.views import del_users

urlpatterns = [
    url('^city_list/', city_list, name='city_list'),
    url('^del_node/', del_node, name='del_node'),
    url('^turf_cartridge/', turf_cartridge, name='turf_cartridge'),
    url('^del_users/', del_users, name='del_users'),
    url('^ajax_add_session_items/', ajax_add_session_items, name='ajax_add_session_items'),
    url('^ajax_add_session_items_from_barcode/', ajax_add_session_items_from_barcode, name='ajax_add_session_items_from_barcode'),
    url('^clear_session/', clear_session, name='clear_session'),
    url('^transfer_to_stock/', transfer_to_stock, name='transfer_to_stock'),
    url('^transfer_to_basket/', transfer_to_basket, name='transfer_to_basket'),
    url('^del_firm/', del_firm, name='del_firm'),
    url('^names_suggests/', names_suggests, name='names_suggests'),
    url('^get_cart_ou/', get_cart_ou, name='get_cart_ou'),
    url('^move_to_use/', move_to_use, name='move_to_use'),
    url('^view_events/', view_events, name='view_events'),
    url('^transfer_to_firm/', transfer_to_firm, name='api_transfer_to_firm'),
    url('^from_basket_to_stock/', from_basket_to_stock, name='from_basket_to_stock'),
    url('^change_ou_name/', change_ou_name, name='change_ou_name'),
    url('^add_object_to_basket_for_firm/', add_object_to_basket_for_firm, name='add_object_to_basket_for_firm'),
    url('^force_move_to_transfer/', force_move_to_transfer, name='force_move_to_transfer'),
    url('^remove_session_item/', remove_session_item, name='remove_session_item'),
    url('^move_objects_to_firm_with_barcode/', move_objects_to_firm_with_barcode, name='move_objects_to_firm_with_barcode'),
    url('^add_object_to_basket_from_firm_to_stock/', add_object_to_basket_from_firm_to_stock, name='add_object_to_basket_from_firm_to_stock'),
    url('^rate/', rate, name='rate'),
    url('^change_cart_number/', change_cart_number, name='change_cart_number'),
    url('^clear_basket_session/', clear_basket_session, name='clear_basket_session'),
]
